# From https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template/blob/master/.github/workflows/main.yml
name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      # Substitute the Manifest and Download URLs in the "module.json"
      # for a FULL RELEASE
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_release_manifest_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{github.event.release.tag_name}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

      # Install packages.
      - run: npm install

      # Build distribution.
      - run: npm run build

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./module.zip module.json index.js index.js.map style.css assets/ dist/ lang/ packs/ animationPNG/ htmlTemplate/ LICENSE AUTHORS README.md

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitDraftDuringUpdate: true
          name: ${{ github.event.release.name }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}